### ISSUE TITLE
Can I ask about a license of this code?

### ISSUE THREAD

**Issue by LunaJang** [nathansmith339/WeatherAPI#1]
Hello, I'm a student who studying computer science...

In class, we carry out a project using opensource to make a program which can tell the weather and find your amazing code.

Can we use and add more function your source in our project?

Excuse me if I was rude or do something wrong because of inexperience of opensource... QQ
(and a lack of English)

**Comment by nevarek** [comment]
If you wish, you're welcome to fork the project to build upon it. You will need to get a new API key from OpenWeather, they provide them for free with an account. You will need to replace my API key with your own.

Depending on the scope of what you need to learn, if you find my project helpful, that's great. I see no reason to forbid you using the code.

I must warn you that using unfamiliar code without the intent of learning how it works will not be beneficial in the long run.

Good luck :)

**Comment by LunaJang** [comment]
Thank you so much!!

After understand your code first, we will use it to follow your advice :)

Thanks once again!!!
